server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"

gateway-prop:
  cookieNameJWT: "JWT"
  excludedUrls: exc
  validationURI: lb://AUTHENTICATION-SERVICE/api/auth/v1/gateway/validation

spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
      routes:
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/api/auth/**
        - id: news-service
          uri: lb://news-service
          predicates:
            - Path=/api/news/**
          filters:
            - PreAuthFilter