server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"

gateway-prop:
  cookieNameJWT: "JWT"
  excludedUrls: exc
  validationURI: lb://AUTHENTICATION-SERVICE/secured/validation

spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
      routes:
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/public/auth/**,/secured/**,/public/token/**
        - id: business-service
          uri: lb://business-service
          predicates:
            - Path=/test/**
          filters:
            - PreAuthFilter