server:
  port: 9001
  servlet:
    context-path: /api/auth

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"

spring:
  data:
    mongodb:
      name: USER_DB
      uri: mongodb+srv://AdminDB:W39ZpY0PCDil2RJw@cluster0.u5rct18.mongodb.net/USER_DB?retryWrites=true&w=majority
  mail:
    host: smtp.gmail.com
    port: 587
    username: projecttestemail98@gmail.com
    password: jdssdqotnhfzzeew
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

token:
  refresh:
    cookie_name: "RefreshToken"
    hoursLength: 1
  jwt:
    cookie_name: "JWT"
    secret_key: "/zqoQPuHhmPtCLUbKMD1jJ8HzW1G2KXNRrkGKBACMRNFQOVLDU5bgC/LgmTdjk3V"
    secondsLength: 900
