server:
  port: 9001
  servlet:
    context-path: /api/auth/v1

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"

spring:
  data:
    mongodb:
      name:
      uri:
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password: 
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

token:
  refresh:
    cookie_name: "RefreshToken"
    hoursLength: 1
  jwt:
    cookie_name: "JWT"
    secret_key: "/zqoQPuHhmPtCLUbKMD1jJ8HzW1G2KXNRrkGKBACMRNFQOVLDU5bgC/LgmTdjk3V"
    secondsLength: 900
