server:
  port: 9002
  servlet:
    context-path: /api/news/v1
  multipart:
    max-file-size: 3MB
    max-request-size: 4MB

eureka:
  instance:
    prefer-ip-address: true

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://root:mysqlpw@localhost:49153/news
    driver-class-name: com.mysql.cj.jdbc.Driver