spring:
  application:
    name: news-service-test
  config:
    import: "optional:configserver:"
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: HSQL
    properties:
      hibernate:
        dialect : org.hibernate.dialect.HSQLDialect

eureka:
  client:
    enabled: false
